sudo: required
dist: trusty
language: c
compiler:
- gcc
before_install:
# for gcc with C++11 support
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get -qq update
install:
- sudo apt-get -qq install ncurses-dev 
- sudo apt-get -qq install libreadline-dev
# install latest LCOV (1.9 was failing)
- cd ${TRAVIS_BUILD_DIR}
- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar xf lcov_1.11.orig.tar.gz
- sudo make -C lcov-1.11/ install
- gem install coveralls-lcov
- lcov --version
- gcc --version
before_script:
- cd ${TRAVIS_BUILD_DIR}
# init coverage to 0 (optional)
- lcov --directory . --zerocounters
script:
- cd ${TRAVIS_BUILD_DIR}
# Check that this works this way
- aclocal
- autoconf
- automake --add-missing
- ./configure
- make
